package com.auracommunityact.missiongtamobile.storage

enum class ResourceStatus(val displayName: String) {
    NOT_CONFIGURED("NOT CONFIGURED"),
    SELECTED("SELECTED"),
    SCANNING("SCANNING..."),
    READY("READY"),
    MISSING_REQUIRED_RESOURCES("MISSING REQUIRED RESOURCES"),
    ACCESS_DENIED("ACCESS DENIED"),
    DIRECTORY_NOT_FOUND("DIRECTORY NOT FOUND"),
    RUNTIME_INCOMPATIBLE("RUNTIME INCOMPATIBLE"),
    VALIDATION_ERROR("VALIDATION ERROR")
}
