package com.example.storage

enum class ResourceStatus(val displayName: String) {
    NOT_CONFIGURED("NOT CONFIGURED"),
    VALIDATING("VALIDATING..."),
    ACCESS_DENIED("ACCESS DENIED"),
    DIRECTORY_NOT_FOUND("DIRECTORY NOT FOUND"),
    MANIFEST_NOT_FOUND("MANIFEST NOT FOUND"),
    INVALID_MANIFEST("INVALID MANIFEST"),
    MISSING_FILES("MISSING FILES"),
    READY("READY")
}
